---
kind: ReplicationController
apiVersion: v1
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 1
  selector:
    app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: green
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - name: http-server
          containerPort: 80
